### ISSUE TITLE
Mono to .NET Core

### ISSUE THREAD

**Issue by jalew188** [MannLabs/alpharaw#80]

**Comment by mschwoer** [comment]
I played around with dotnet here: https://github.com/MannLabs/alpharaw/tree/dotnet_attempt

for Thermo, I get the error message below. 
Seems like this requires .NET Framework (=windows only) and does not work with .NET core.


```
ErrorCode -1
ErrorMessage Encountered problems while trying to read '' as a Raw File!

Exception type: System.MissingMethodException
Message       : Method not found: 'Void System.Threading.Mutex..ctor(Boolean, System.String, Boolean ByRef, System.Security.AccessControl.MutexSecurity)'.
Stacktrace:
   at ThermoFisher.CommonCore.RawFileReader.Utilities.CreateNamedMutexAndWait(String fileName, Boolean useGlobalNamespace, DeviceErrors errors)
   at ThermoFisher.CommonCore.RawFileReader.Facade.RawFileLoader..ctor(String fileName)
```

**Comment by mschwoer** [comment]
For sciex, I get the following

```
  File "/app/alpharaw/sciex.py", line 44, in _import
    wiff_reader = pysciexwifffilereader.WillFileReader(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/alpharaw/raw_access/pysciexwifffilereader.py", line 47, in __init__
    self.sample_names = self._wiff_file.GetSampleNames()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #8': Invalid managed/unmanaged type combination (Marshaling to and from COM interface pointers isn't supported).
   at Clearcore2.StructuredStorage.COM.StgFunctions.StgOpenStorageEx(String pwcsName, UInt32 grfMode, UInt32 stgfmt, UInt32 grfAttrs, IntPtr pStgOptions, IntPtr reserved2, Guid& riid, Object& ppObjectOpen)
   at Clearcore2.StructuredStorage.COM.StgFunctions.OpenStorage(String filePath, StgMode mode)
   at Clearcore2.StructuredStorage.StgStorageCOM.OpenFileCOM(String filePath, StgMode mode, Object cacheKey)
   at Clearcore2.StructuredStorage.StgStorage.OpenFile(String filePath, StgMode mode, Object cacheObject)
   at Clearcore2.Data.WiffReader.WiffStorageProviderDefaultImplementation.OpenFile()
   at Clearcore2.Data.WiffReader.WiffStorage..ctor(IWiffStorageProvider storage)
   at Clearcore2.Data.WiffReader.WiffStorageOwner.GetWiffStorage()
   at Clearcore2.Data.WiffReader.WiffStorageOwner.get_WiffStorage()
   at Clearcore2.Data.WiffReader.WiffStorageOwner.GetWiffStorage()
   at Clearcore2.Data.WiffReader.WiffStorageOwner.get_WiffStorage()
   at Clearcore2.Data.WiffReader.WiffSampleSubTree.get_SampleCount()
   at Clearcore2.Data.WiffReader.WiffFile.get_SampleCount()
   at Clearcore2.Data.AnalystDataProvider.AnalystWiffDataProvider.GetBasicSampleInfos(String pathToSourceFile)
   at Clearcore2.Data.AnalystDataProvider.BatchImp.GetSampleNames()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
